--- # Creating Targets for the Servers
- hosts: frontend
  user: ubuntu
  become: yes
  connection: ssh
  roles:
      - frontend_server

- hosts: backend_mysql
  user: ubuntu
  become: yes
  connection: ssh
  roles:
      - backend_server_mysql

