--- # Creating LOOP playbook
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks: 
      - name: Creating multiple folders
        file:
          path: "/home/ansible/{{ item }}"
          state: directory
          mode: "0755"
        loop:  # Here you can use both loop or with_items
          - Arnab
          - Nobu
          - Mou
          - Abhi
